program = statement* EOF ;
statement = expression_statement | echo_statement ;
echo_statement = "echo" expression ";" ;
expression_statement = expression ";" ;
expression = equality;
equality = comparison ( ( "!=" | "==") comparison )* ;
comparsion = term ( (">" | ">=" | "<" | "<=") term)* ;
term = factor ( ("-" | "+") factor )* ;
factor = unary ( ("/" | "*") unary )* ;
unary = ( "-" | "!" ) unary | primary ;
primary = NUMBER | STRING | "true" | "false" | "nil" | group ;